### ISSUE TITLE
File structure

### ISSUE THREAD

**Issue by sagikazarmark** [K-Phoen/SitemapGenerator#10]
Regarding interfaces (BC is broken already): I think it is better not to include interfaces in the namespace where implementations are. I have a few reasons for it:
1. `Some\Name\Space\Provider\Provider` is somewhat redundant. `Some\Name\Space\Provider` seems cleaner to me.
2. It is a common pattern to treat subnamespaces like a collection of implementations of an interface, meaning if the interface is Provider, then all classes in the provider namespace are either Provider implementations or related helpers (traits, etc).

**Comment by K-Phoen** [comment]
Yeah, you're absolutely right.

I just left the interfaces where they were because I want to think about the architecture of the library. There are a few things that currently bother me (like the SitemapIndex support for instance) and I might change a few things in the library to improve that. I'll move these interfaces at that time I think.

P.S : I broke the backward compatibility because the next release will be be 2.0 and not 1.x

**Comment by sagikazarmark** [comment]
:+1: 

> P.S : I broke the backward compatibility because the next release will be be 2.0 and not 1.x

No problem with that, I meant that any more changes should be done before 2.0 stable, because BC is broken anyway.

**Comment by K-Phoen** [comment]
Done.
